//****************************************************************************************************************
//	This is an example of an externalized include file.
//****************************************************************************************************************
call TSEEQ_Trace('Entering Include File: $(vApp)CalendarCreation.qvs');
// Add script here as required.
    SET vTSEEQ_FactTableDateField='Date';
    SET vTSEEQ_CalendarFieldNamePrefix='';

AllDates:   
//  2026-05-24 JRR commented the following line for https://github.com/qlikperf/TSEEQ/issues/21
//  Load FieldValue('$(vTSEEQ_FactTableDateField)',IterNo()) as TSEEQ_DateDistinct
//  2026-05-24 JRR added the following line for https://github.com/qlikperf/TSEEQ/issues/21
Load date#(FieldValue('$(vTSEEQ_FactTableDateField)',IterNo()), '$(DateFormat)' ) as TSEEQ_DateDistinct
AutoGenerate(1)
While not Isnull(FieldValue('$(vTSEEQ_FactTableDateField)',IterNo()));

MinMaxDates:
Load 
    Max(TSEEQ_DateDistinct) as MaxTSEEQ_Date,		// latest date in Fact Table
    date(Max(TSEEQ_DateDistinct)) as MaxTSEEQ_DateFormatted,		// latest date in Fact Table
    Min(TSEEQ_DateDistinct) as MinTSEEQ_Date    	// earliest date in Fact Table
resident AllDates;
Drop table AllDates; 

// Prior to generating the calendar, read Variables file for values of vMinDateNum, vMaxDateNum and vToday:
call Load_Variables_from_XLS('$(vVariablePath)$(vApp)_Date_Variables.xls', 'Sheet1', 'KEEP') ;

//  2022-07-07 JRR cchanged 'createcalendartable' to 'CreateCalendarTable', for SaaS / CloudBucket support: 
$(must_Include=$(vCommonScriptPath)CreateCalendarTable.txt); 
call CreateCalendarQvd('$(vTSEEQ_CalendarFieldNamePrefix)', 'KEEP');			// Create Calendar and then keep the calendar in memory.    

SET vMinDateNum=;
SET vMaxDateNum=;
SET vTSEEQ_FactTableDateField=;
SET vTSEEQ_CalendarFieldNamePrefix=;
DROP Table MinMaxDates;

call TSEEQ_Trace('Exiting Include File: $(vApp)CalendarCreation.qvs');